#!/bin/bash

echo "🧪 Live Chat Socket Test"
echo "======================="
echo ""
echo "📋 Instructions for testing:"
echo "1. Open http://localhost:5000 in TWO different browser tabs/windows"
echo "2. Login with different users in each tab:"
echo "   - Tab 1: admin@test.com / password123"
echo "   - Tab 2: member@test.com / password123"
echo ""
echo "3. After logging in both users:"
echo "   - Select a workspace in the navbar"
echo "   - Click on the other user in the left panel"
echo "   - Start typing messages in the chat"
echo ""
echo "✅ Expected behavior:"
echo "   - Messages should appear instantly in both tabs without refreshing"
echo "   - Online users should show in the Socket Test component"
echo "   - Backend console should show socket message logs"
echo ""
echo "🔍 Troubleshooting:"
echo "   - Check browser console for any errors"
echo "   - Verify socket connection status in Socket Test component"
echo "   - Backend logs should show message broadcasting"
echo ""
echo "Backend is running on: http://localhost:3000"
echo "Frontend is running on: http://localhost:5000"
